spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dt2tl
    username: dt2tl
    password: dt2tl
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info
    com.jbtits: ${log_jbtits:info}
botapi:
  token: ${botapi_token}
  username: ${botapi_username}

